### ISSUE TITLE
Not be reactive when using vue data in reactiveData

### ISSUE THREAD

**Issue by zhongqf** [Grottolabs/vue-meteor-data#2]
Consider this

```
module.exports = {
    data: function() {
        return {
            taskId: 'anID'
        }
    },  
    reactiveData   : {
        task: function () {
            return Tasks.findOne(this.taskId)
        }
    },
    created: function(){
        this.subscribe('tasks/all')
    }
}    
```

`task` will not be updated even taskId was changed.
So it only be reactive with Meteor, not Vue itself.

**Comment by jakobrosenberg** [comment]
I'll see if I can find a solution to this. Feedback is more than welcome. ;)

**Comment by almini** [comment]
Check out my plugin, it might help: [vue-meteor](https://github.com/almini/vue-meteor).

**Comment by zhongqf** [comment]
Thanks @almini 

A question:
As my understanding,   `$track`/`dataReactive` will track both Meteor and Vue reactive sources (Collection, Session, variables), while `$trackMeteor`/`dataMeteor` will track Meteor only. Is it right?
Why should I use `$trackMeteor`/`dataMeteor`?

**Comment by almini** [comment]
Yes you are right. $trackMeteor and dataMeteor are less computationally expensive.

**Comment by jakobrosenberg** [comment]
Reactivity has been added for Vue in version 1.0.5. This works for both vm.reactiveData and vm.autorun.

**Comment by jakobrosenberg** [comment]
@almini thanks for the input.
