### ISSUE TITLE
Meteor Collections

### ISSUE THREAD

**Issue by aronsuarez** [Grottolabs/vue-meteor-data#3]
Hi,

I have setup a vue project add meteor-client side package, then i add the vue-meteor-data package.

Now how ca i get data from meteor server?
When i call Meteor.status().connected is the status true.
But i can't acces the data with the vue-meteor-package, i think is a problem that the collection not present, but when i try to create the collection Tasks = new Mongo.Collection('tasks') i become the error from webpack Tasks is not definied.

Pleas pleas help

thank you

**Comment by fallenpeace** [comment]
Do you have a repository or example code you could show us?

Short answer: Make sure you're publishing your collections.

**Comment by aronsuarez** [comment]
Yep i have a repo on my account (is the only repo on my account). The collection is pushed but where on the client side i need to subscribe? on a meteor project is clear but where i do this with meteor-client package?

**Comment by jakobrosenberg** [comment]
Your project is giving me errors after `npm install` and `npm run dev`. If you resolve them, I can give your project another look.

Alternatively you can also integrate Meteor like this:
https://github.com/vuejs/vue-webpack-meteor-example

EDIT: Your source files have unresolved dependencies. You need to import and export the modules you use.

As the issues you're experiencing are unrelated to this mixin, I'm closing the issue. If you think I missed something, please let me know. For now I suggest you contact the author of "meteor-client-side" or try the above alternative.

**Comment by aronsuarez** [comment]
Thanks for help, i have found the problem. I need to put the new Mongo.Collection in a Global Variable. The errors are no problem this only code design error from webpack like this: To much spacec between abcd:   function... the code runs also
