### ISSUE TITLE
Tracking things like Meteor.user()

### ISSUE THREAD

**Issue by fallenpeace** [Grottolabs/vue-meteor-data#4]
How would you recommend tracking things like Meteor.user() and Meteor.user().username.

Sometimes, Meteor.user().username will error out because the userData hasn't been sent down to the client yet, any way you recommend to approach this? Currently doing this, however it runs 2 or 3 times when initially loading the page and feels super hacky.

``` javascript
dataReactive: {
            //relying on the fact this property updates when meteor deps change,
            //dispatches an actions that mutates the state tree in vuex
            checkAuth: function () {
                if (!!Meteor.user() && !!Meteor.userId()) {
                     console.log("ALREADY LOGGED IN: SETTING AUTH")
                    store.actions.checkAuth(Meteor.userId());
                    return true;
                } else {
                    console.log("NOT LOGGED IN YET");
                    store.actions.checkAuth(null);
                    return false;
                }


            }

        }
```

Also, when publishing extra userData, the Meteor.user() is available before the custom userData is merged with the user object, is their a recommended approach to wait for that, so events aren't firing off 3+ times on initial page loads?

**Comment by jakobrosenberg** [comment]
When a view is created, the mixin iterates through `dataReactive` and wraps each of its functions in Vue's `vm.$watch`. Then each of these functions are wrapped in Meteor's `Tracker.autorun`. Later when/if the view is destroyed, the view stops the trackers.

All in all, the mixin is a thin wrapper for each tracker and the issue with Meteor.user() returning data progressively has (at least for me) always been part of making Meteor apps.

After all, the issue isn't that the tracker is tracking too early or too much, but that Meteor.user() reports prematurely before it has the data we want. One solution might be to create a serverside wrapper or tracker for Meteor.user() that tells you when your data is ready.

Moving the `Meteor.userId()` check to the mixin itself is also an option, but I don't know if that would be wise.

**Comment by fallenpeace** [comment]
Awesome thanks for the advice You have a point with Meteor's progressive stream of data, I figured it'd be less stressful to just mutate my state as the `Meteor.user()` object changes and not worry about whether it has ALL the data, since it will eventually arrive, and I can just check against my state tree for it if I ever need it before a certain operation.

**Comment by jakobrosenberg** [comment]
Happy to help.

By the way, did you consider moving Meteor.userId() to your store?

`vue file`

```
dataReactive: {
  checkAuth: store.actions.checkAuth();
}
```

`action file`

```
export default {
  checkAuth: ({context})=>{
    if ( Meteor.user() && Meteor.userId() )
      //return check against userId
    else
      return false
  }
}
```
